from PyQt5 import QtCore, QtGui, QtWidgets
import icon


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.setWindowModality(QtCore.Qt.WindowModal)
        mainwindow.resize(550, 200)
        mainwindow.setMinimumSize(QtCore.QSize(550, 200))
        mainwindow.setMaximumSize(QtCore.QSize(550, 200))
        mainwindow.setStyleSheet("background-image: url(:/resources/bck.png);")

        def say_hello():
            print("Button clicked, Hello!")

        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open = QtWidgets.QToolButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.open.setAutoFillBackground(False)
        self.open.setStyleSheet("image: url(:/resources/open.png);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open.setIcon(icon)
        self.open.setIconSize(QtCore.QSize(64, 64))
        self.open.setObjectName("open")
        self.compress = QtWidgets.QToolButton(self.centralwidget)
        self.compress.setGeometry(QtCore.QRect(130, 10, 71, 71))
        self.compress.setAutoFillBackground(False)
        self.compress.setStyleSheet("image: url(:/resources/open.png);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/compress.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compress.setIcon(icon1)
        self.compress.setIconSize(QtCore.QSize(64, 64))
        self.compress.setObjectName("compress")
        self.extract = QtWidgets.QToolButton(self.centralwidget)
        self.extract.setGeometry(QtCore.QRect(250, 10, 71, 71))
        self.extract.setAutoFillBackground(False)
        self.extract.setStyleSheet("image: url(:/resources/open.png);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/extract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extract.setIcon(icon2)
        self.extract.setIconSize(QtCore.QSize(64, 64))
        self.extract.setObjectName("extract")
        self.exit = QtWidgets.QToolButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(350, 20, 61, 61))
        self.exit.setAutoFillBackground(False)
        self.exit.setStyleSheet("image: url(:/resources/open.png);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon3)
        self.exit.setIconSize(QtCore.QSize(64, 64))
        self.exit.setObjectName("exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setFamily("11S01 Black Tuesday Italic")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("11S01 Black Tuesday Italic")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("11S01 Black Tuesday Italic")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 80, 21, 21))
        font = QtGui.QFont()
        font.setFamily("11S01 Black Tuesday Italic")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.menubar.setObjectName("menubar")
        self.menuFicheiro = QtWidgets.QMenu(self.menubar)
        self.menuFicheiro.setObjectName("menuFicheiro")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(mainwindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionExtrair = QtWidgets.QAction(mainwindow)
        self.actionExtrair.setObjectName("actionExtrair")
        self.actionComprimir = QtWidgets.QAction(mainwindow)
        self.actionComprimir.setObjectName("actionComprimir")
        self.actionSair = QtWidgets.QAction(mainwindow)
        self.actionSair.setObjectName("actionSair")
        self.menuFicheiro.addSeparator()
        self.menuFicheiro.addAction(self.actionAbrir)
        self.menuFicheiro.addSeparator()
        self.menuFicheiro.addAction(self.actionExtrair)
        self.menuFicheiro.addAction(self.actionComprimir)
        self.menuFicheiro.addAction(self.actionSair)
        self.menubar.addAction(self.menuFicheiro.menuAction())

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "PandaZipper© Alpha 0634.22 "))
        self.open.setText(_translate("mainwindow", "..."))
        self.compress.setText(_translate("mainwindow", "..."))
        self.extract.setText(_translate("mainwindow", "..."))
        self.exit.setText(_translate("mainwindow", "..."))
        self.label.setText(_translate("mainwindow", "Abrir Ficheiro"))
        self.label_2.setText(_translate("mainwindow", "Comprimir Ficheiro"))
        self.label_3.setText(_translate("mainwindow", "Extrair Ficheiro"))
        self.label_4.setText(_translate("mainwindow", "Sair"))
        self.menuFicheiro.setTitle(_translate("mainwindow", "Ficheiro"))
        self.actionAbrir.setText(_translate("mainwindow", "Abrir"))
        self.actionExtrair.setText(_translate("mainwindow", "Extrair"))
        self.actionComprimir.setText(_translate("mainwindow", "Comprimir"))
        self.actionSair.setText(_translate("mainwindow", "Sair"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
